
PUT http://localhost:3003/api/blogs/64bbe1af1a2d663473159cca
Content-Type: application/json

{
        "id": "64bbe1af1a2d663473159cca",
        "title": "bunbuub",
        "author": "klubuuuuuwetska",
        "url": "nobobwwwwwwobo.com",
        "likes": 324
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "matislav",
    "name": "bambini",
    "password": "mati123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "it",
    "author": "stephen king",
    "url": "ububub.com",
    "likes": 666,
    "userId": "64bea944d0675caf798838f7"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "matislav",
    "password": "mati123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGlzbGF2IiwiaWQiOiI2NGJlYTk0NGQwNjc1Y2FmNzk4ODM4ZjciLCJpYXQiOjE2OTAyMjQ2NTV9.gespUjdnzy580fEqfqqoAu4j9uY2aELA43miO-EiHbM

{
 "title": "Bayern signs Kim MinJae!",
 "author": "Fabrizio Romano",
 "url": "twitter.com",
 "likes": 666
}

###

DELETE http://localhost:3003/api/blogs/64bea982d0675caf798838fe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGlzbGF2IiwiaWQiOiI2NGJlYTk0NGQwNjc1Y2FmNzk4ODM4ZjciLCJpYXQiOjE2OTAyMzkwNDB9.e2hcDOMSP62OXWMGjFEFrbt-A17mqwMjRYE2IiOkGsU