POST http:/mongodb+srv://mateuszkuruc:defenestracja12@cluster0.xuvl4j3.mongodb.net/testBlogApp?retryWrites=true&w=majority
Content-Type: application/json

{
    title: "Blog1",
    author: "Matiautor",
    url: "bing.com",
    likes: 4,
}

###

PUT http://localhost:3003/api/blogs/64bbe1af1a2d663473159cca
Content-Type: application/json

{
        "id": "64bbe1af1a2d663473159cca",
        "title": "bunbuub",
        "author": "klubuuuuuwetska",
        "url": "nobobwwwwwwobo.com",
        "likes": 324
}