POST http://localhost:3001/api/notes Content-Type: application/json

{
"important": true
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "nooooo nie wiem test",
    "important": true,
    "userId": "64bbf07325e6e2dc48262f3c"
}