POST http://localhost:3001/api/notes Content-Type: application/json

{
"important": true
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mati",
    "name": "bubens",
    "password": "mati123"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "nooooo nie wiem test",
    "important": true,
    "userId": "64bbf07325e6e2dc48262f3c"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mati",
    "password": "mati123"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdGkiLCJpZCI6IjY0YmUzYjM1NDkxYTA1NzAxZjkyOTY3NCIsImlhdCI6MTY5MDE5MzE1MH0.jrBDojGr7ILAOKDr3cL4tbHsTLudDM2pwwgVG6nqoMM

{
    "content": "single page apps use token authorization",
    "important": true
}